<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Appseconnect\B2BMage\Block\Customer\Form\Register $block */
/** @var \Magento\Customer\ViewModel\Address $viewModel */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$viewModel = $block->getViewModel();
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<?php $_country_id = $block->getAttributeData()->getFrontendLabel('country_id'); ?>
<?php $_street = $block->getAttributeData()->getFrontendLabel('street'); ?>
<?php $_city = $block->getAttributeData()->getFrontendLabel('city'); ?>
<?php $_region = $block->getAttributeData()->getFrontendLabel('region'); ?>
<?php $_selectRegion = 'Please select a region, state or province.'; ?>
<?php $_displayAll = $block->getConfig('general/region/display_all'); ?>

<?php $_vatidValidationClass = $viewModel->addressGetAttributeValidationClass('vat_id'); ?>
<?php $_cityValidationClass = $viewModel->addressGetAttributeValidationClass('city'); ?>
<?php $_postcodeValidationClass_value = $viewModel->addressGetAttributeValidationClass('postcode'); ?>
<?php $_postcodeValidationClass = $_postcodeValidationClass_value; ?>
<?php $_streetValidationClass = $viewModel->addressGetAttributeValidationClass('street'); ?>
<?php $_streetValidationClassNotRequired = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
<?php $_regionValidationClass = $viewModel->addressGetAttributeValidationClass('region'); ?>
<form class="form create account form-create-account" action="<?= $this->getUrl('b2bmage/customer/savepost', ['_secure' => true]); ?>" method="post"
      id="form-validate" enctype="multipart/form-data" autocomplete="off" novalidate="novalidate">
    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey(); ?>"/>
    <fieldset class="fieldset account">
        <legend class="legend"><span><?= __("Company Information") ?></span></legend>
        <br>
        <div class="field field-name-firstname required">
            <label class="label" for="company_name">
                <span><?= __("Company Legal Name") ?></span>
            </label>
            <div class="control">
                <input type="text" id="company_firstname" name="company_firstname" value="" title="<?= __("Company Name") ?>"
                       class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                       aria-required="true">
            </div>
        </div>

        <div class="field field-name-email required">
            <label class="label" for="company_name">
                <span><?= __("Company Email") ?></span>
            </label>
            <div class="control">
                <input type="text" id="company_email" name="company_email" value="" title="<?= __("Company Email") ?>"
                       class="input-text required-entry" data-validate="{required:true, 'validate-email':true}"
                       autocomplete="off" aria-required="true">
            </div>
        </div>


        <?php $dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?= $dob->toHtml() ?>

    </fieldset>

    <fieldset class="fieldset address">
        <legend class="legend"><span><?= __("Company Address") ?></span></legend>
        <br>
        <div class="field street required">
            <label for="street_1" class="label">
                <span><?= __("Street Address") ?></span>
            </label>
            <div class="control">
                <input address="true" type="text" name="address[street][1]" value=""
                       title="<?= __("Street Address") ?>" id="street" position="1" identifier="street"
                       class="input-text required-entry" aria-required="true">
                <div class="nested">
                    <div class="field additional">
                        <label class="label" for="street_2">
                            <span><?= __("Street Address 2") ?></span>
                        </label>
                        <div class="control">
                            <input address="true" type="text" name="address[street][2]" value=""
                                   title="<?= __("Street Address 2") ?>" position="2" id="street_2"
                                   class="input-text street" aria-required="true">
                        </div>
                    </div>
                    <div class="field additional">
                        <label class="label" for="street_3">
                            <span><?= __("Street Address 3") ?></span>
                        </label>
                        <div class="control">
                            <input address="true" type="text" name="address[street][3]" value=""
                                   title="<?= __("Street Address 3") ?>" position="3" id="street_3"
                                   class="input-text street" aria-required="true">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="field field-name-telephone required">
            <label class="label" for="company_name">
                <span><?= __("Company Telephone") ?></span>
            </label>
            <div class="control">
                <input type="text" id="telephone" name="telephone" value=""
                       title="<?= __("Company Telephone") ?>" class="input-text required-entry"
                       data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div>


        <div class="field country required">
            <label class="label" for="country">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
            </label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= /* @noEscape */ $_region ?></span>
            </label>
            <div class="control">
                <select id="region_id" name="region_id"
                        title="<?= /* @noEscape */ $_region ?>"
                        class="validate-select region_id"
                    <?= /* @noEscape */ !$_displayAll ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $escaper->escapeHtml(__($_selectRegion)) ?></option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value=""
                       title="<?= /* @noEscape */ $_region ?>"
                       class="input-text validate-not-number-first
                        <?= $escaper->escapeHtmlAttr($_regionValidationClass) ?>"
                    <?= !$_displayAll ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="city"
                       value=""
                       title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= $escaper->escapeHtmlAttr($_cityValidationClass) ?>"
                       id="city">
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value=""
                       title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                       id="zip"
                       class="input-text validate-zip-international
                        <?= $escaper->escapeHtmlAttr($_postcodeValidationClass) ?>">
                <div role="alert" class="message warning">
                    <span></span>
                </div>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div.message.warning') ?>
            </div>
        </div>





        <div class="field choice set billing">
            <input address="true" type="checkbox" id="default_billing" originalName="default_billing"
                   name="address[default_billing]" value="1" class="checkbox billing">
            <label class="label" for="primary_billing">
                <span>Use as my default billing address</span>
            </label>
        </div>
        <div class="field choice set shipping">
            <input address="true" type="checkbox" id="default_shipping" originalName="default_shipping"
                   name="address[default_shipping]" value="1" class="checkbox shipping">
            <label class="label" for="primary_shipping">
                <span>Use as my default shipping address</span>
            </label>
        </div>
    </fieldset>

    <br/>
    <fieldset class="fieldset account">
        <legend class="legend"><span><?= __("Contact Person Information") ?></span></legend>
        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span><?= __("First Name") ?></span>
            </label>

            <div class="control">
                <input type="text" id="firstname" name="firstname" value="" title="<?= __("First Name") ?>"
                       class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                       aria-required="true">
            </div>
        </div>
        <div class="field field-name-lastname required">
            <label class="label" for="lastname">
                <span><?= __("Last Name") ?></span>
            </label>

            <div class="control">
                <input type="text" id="lastname" name="lastname" value="" title="<?= __("Last Name") ?>"
                       class="input-text required-entry" data-validate="{required:true}" autocomplete="off"
                       aria-required="true">
            </div>
        </div>
        <div class="field field-name-lastname required">
            <label class="label" for="lastname">
                <span><?= __("Contact Email") ?></span>
            </label>

            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address" value=""
                       title="<?= __("Email") ?>" class="input-text"
                       data-validate="{required:true, 'validate-email':true}" aria-required="true">
            </div>
        </div>



        <div class="field password required">
            <label class="label" for="lastname">
                <span><?= __("Password") ?></span>
            </label>

            <div class="control">
                <input type="password" name="password" id="password"
                       title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                       class="input-text"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirmation required">
            <label for="password-confirmation"
                   class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
            <div class="control">
                <input type="password" name="password_confirmation"
                       title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation"
                       class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?= __("Create an Account") ?>">
                <span><?= __("Create an Account") ?></span></button>
        </div>
    </div>
</form>


<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }


</script>
</script>
<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }


</script>

