<?php

// @codingStandardsIgnoreFile

/**
 * @var $block \Appseconnect\B2BMage\Block\Quotation\Quote\Totals
 * @see \Appseconnect\B2BMage\Block\Quotation\Quote\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php /* @noEscape */ echo $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else:?>
    <tr class="<?php /* @noEscape */ echo $_code ?>">
        <th <?php /* @noEscape */ echo $block->getLabelProperties() ?> scope="row">
            <?php if ($_total->getStrong()):?>
            <strong><?php /* @noEscape */ echo $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else:?>
            <?php /* @noEscape */ echo $block->escapeHtml($_total->getLabel()) ?>
            <?php endif?>
        </th>
        <td <?php /* @noEscape */ echo $block->getValueProperties() ?> data-th="<?php /* @noEscape */ echo $block->escapeHtml($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()):?>
            <strong><?php /* @noEscape */ echo $block->formatValue($_total) ?></strong>
            <?php else:?>
            <?php /* @noEscape */ echo $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach?>
