<?php
$contactPersonId = $block->getRequest()->getParam('id');
?>

<form class="form create account form-create-account"
  action=<?php /* @noEscape */ echo $block->getUrl('b2bmage/contact/index_createPost')?>
 method="post" id="form-validate" enctype="multipart/form-data"
 autocomplete="off">
    <fieldset class="fieldset create info">
        <legend class="legend">
            <span>Personal Information</span>
      </legend>
      <br> <input type="hidden"
          value="<?php /* @noEscape */ echo $contactPersonId?>"
          name="contactperson_id" id="contactperson_id" /> <input type="hidden"
          name="success_url" value=""> <input type="hidden" name="error_url"
         value="">
      <div class="field field-name-status required">
         <label class="label" for="status"> <span>Status</span>
         </label>

          <div class="control">

             <select class="required-entry select" name="status" id="status">
                   <option value="1">Active</option>
                  <option value="0">Inactive</option>
                </select>
          </div>
     </div>
     <div class="field field-name-role required">
            <label class="label" for="role"> <span><?php /* @noEscape */ echo __("Role"); ?></span>
            </label>

            <div class="control">

                <select class="required-entry select" name="role" id="role">
                    <option value="1"><?php /* @noEscape */ echo __("Administrator"); ?></option>
                    <option value="2"><?php /* @noEscape */ echo __("Standard"); ?></option>
                </select>
            </div>
        </div>

        <div class="field field-name-firstname required">
          <label class="label" for="firstname"> <span>First Name</span>
          </label>

          <div class="control">
              <input type="text" id="firstname" name="firstname" value=""
                    title="First Name" class="input-text required-entry"
                   data-validate="{required:true}">
           </div>
     </div>
     <div class="field field-name-lastname required">
           <label class="label" for="lastname"> <span>Last Name</span>
            </label>

          <div class="control">
              <input type="text" id="lastname" name="lastname" value=""
                  title="Last Name" class="input-text required-entry"
                    data-validate="{required:true}">
           </div>
     </div>
 </fieldset>
    <fieldset class="fieldset create account"
      data-hasrequired="* Required Fields">
      <legend class="legend">
            <span>Sign-in Information</span>
       </legend>
      <br>
       <div class="field required">
           <label for="email_address" class="label"><span>Email</span></label>
            <div class="control">
              <input type="email" name="email" autocomplete="email"
                  id="email_address" value="" title="Email" class="input-text"
                   data-validate="{required:true, 'validate-email':true}">
            </div>
     </div>
 </fieldset>
    <div class="actions-toolbar">
      <div class="primary">
          <button type="submit" class="action submit primary"
                title="Create an Account">
             <span><?= __("Save")?></span>
         </button>
      </div>
 </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "contactAdd": {}
        }
    }
</script>
