<?php
/** @var $block \Magento\Backend\Block\Widget\Form */
?>
<?php /* @todo replace .form-inline with better class name */?>
<?php /* ToDo UI: check if we need this wrapper in the process of global forms refactoring */ ?>
<?php
$data = $this->getWarrantyData();
?>
<div class="service_info" style="margin-bottom: 40px;">
<div class="admin__page-section-title">
    <span class="title">Warranty Request & Account Information</span></div>


    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information" style="width: 50%;  ">
            <div class="admin__page-section-title">
                <span class="title">
                    Warranty ID #<?php echo $data['id']; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary ">
                    <tbody>
                        <tr><td>Submitted Date</td><td style="text-align: right;"><?php echo $data['submit_date']; ?></td></tr>
                        <tr><td>Date of purchase</td><td style="text-align: right;"><?php echo $data['date_of_purchase']; ?></td></tr>
                        <tr><td>SKU</td><td style="text-align: right;"><?php echo $data['sku']; ?></td></tr>
                        <tr><td>Serial No.</td><td style="text-align: right;"><?php echo $data['mfr_serial_no']; ?></td></tr>
                        <tr><td>Warranty start date</td><td style="text-align: right;"><?php echo $data['warranty_start_date']; ?></td></tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-information" style="width: 50%;  padding-left: 30px;">
            <div class="admin__page-section-title">
                <span class="title">
                    Account Information
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary ">
                    <tbody>
                    <tr><td>Customer Name</td><td style="text-align: right;"><?php echo $data['customer_name']; ?></td></tr>
                    <tr><td>Email</td><td style="text-align: right;"><?php echo $data['customer_email']; ?></td></tr>
                    <tr><td>Invoice number</td><td style="text-align: right;"><?php echo $data['purchase_order_number']; ?></td></tr>
                    <tr><td>Invoice document</td><td style="text-align: right;">
                            <a target="_blank" href="<?php echo $data['document_path'] . $data['purchase_order_file']; ?>"><?php echo basename($data['purchase_order_file'],'/'); ?></a>
                        </td></tr>
                    <tr><td>Warranty end date</td><td style="text-align: right;"><?php echo $data['warranty_end_date']; ?></td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="entry-edit form-inline">
    <?= $block->getFormHtml() ?>
</div>
<?= $block->getChildHtml('form_after') ?>
