<?php
/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
$salesrepMessage=$block->getMessage();
?>
<?php switch ($block->getShowPart()) :
    case 'welcome':
                ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String('<?php /* @noEscape */ echo $block->escapeHtml(
                __('Welcome, %1!', '%1')
            ).' '.$salesrepMessage;?>').replace('%1', customer().firstname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind="html:'<?php $block->escapeHtml($welcomeMessage).' '.$salesrepMessage ?>'"></span>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php
              break; ?>

    <?php case 'other':
                ?>
        <?php /* @noEscape */ echo $block->getChildHtml(); ?>
    <?php
              break; ?>

<?php endswitch; ?>
