<?php

// @codingStandardsIgnoreFile
/** @var \Appseconnect\B2BMage\Block\Adminhtml\Quotation\Quote\View\History $block */
?>
<div id="quote_history_block" class="edit-order-comments">
    <?php //if ($block->canAddComment()):?>
        <div class="order-history-block" id="history_form">

            

            <div class="admin__field">
                <label for="history_comment" class="admin__field-label">
                    <?php /* @noEscape */ echo __('Comment') ?>
                </label>
                <div class="admin__field-control">
                    <textarea name="history[comment]"
                              rows="3"
                              cols="5"
                              id="history_comment"
                              class="admin__control-textarea"></textarea>
                </div>
            </div>

            <div class="admin__field">
                <div class="order-history-comments-options">
                
                    <div class="admin__field admin__field-option">
                        <input name="history[is_customer_notified]"
                               type="checkbox"
                               class="admin__control-checkbox"
                               id="history_notify"
                               value="1" />
                        <label class="admin__field-label"
                               for="history_notify"><?php /* @noEscape */ echo __('Notify Customer by Email') ?></label>
                    </div>

                    <div class="admin__field admin__field-option">
                        <input name="history[is_visible_on_front]"
                               type="checkbox"
                               id="history_visible"
                               class="admin__control-checkbox"
                               value="1" />
                        <label class="admin__field-label" for="history_visible">
                            <?php /* @noEscape */ echo __('Visible on Storefront') ?>
                        </label>
                    </div>
                </div>

                <div class="order-history-comments-actions">
                    <?php /* @noEscape */ echo $block->getChildHtml('submit_button') ?>
                </div>
            </div>
        </div>
    <?php //endif;?>
    
    
    
    <ul class="note-list">
    <?php foreach ($block->getQuote()->getStatusHistoryCollection(true) as $_item): ?>
        <li class="note-list-item">
            <span class="note-list-date"><?php /* @noEscape */ echo $block->formatDate($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
            <span class="note-list-time"><?php /* @noEscape */ echo $block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
            <span class="note-list-status"><?php /* @noEscape */ echo $_item->getStatusLabel() ?></span>
            <span class="note-list-status name"><?php /* @noEscape */ echo $_item->getName() ?></span>
            <span class="note-list-customer">
                <?php /* @noEscape */ echo __('Customer') ?>
                <?php if ($block->isCustomerNotificationNotApplicable($_item)): ?>
                    <span class="note-list-customer-notapplicable"><?php /* @noEscape */ echo __('Notification Not Applicable') ?></span>
                <?php elseif ($_item->getIsCustomerNotified()): ?>
                    <span class="note-list-customer-notified"><?php /* @noEscape */ echo __('Notified') ?></span>
                <?php else: ?>
                    <span class="note-list-customer-not-notified"><?php /* @noEscape */ echo __('Not Notified') ?></span>
                <?php endif; ?>
            </span>
            <?php if ($_item->getComment()): ?>
                <div class="note-list-comment"><?php /* @noEscape */ echo $block->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?></div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
    
    
    
    

</div>

<script>
require(['prototype'], function(){

        if($('order_status'))$('order_status').update('<?php /* @noEscape */ echo $block->getQuote()->getStatusLabel() ?>');

});
</script>


