<?php

// @codingStandardsIgnoreFile

?>
    <?php  $_quote = $block->getQuote() ?>
    <div class="actions">
        <button type="submit" style="float: right"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?php /* @noEscape */ echo $block->escapeHtml(__('Update')) ?>"
                class="action update quote primary">
            <span><?php /* @noEscape */ echo __('Update') ?></span>
        </button>
    </div>
    <?php /* @noEscape */ echo $block->getChildHtml() ?>
