<?php

// @codingStandardsIgnoreFile

/** @var $block \Appseconnect\B2BMage\Block\Quotation\Quote\Email\Items\DefaultItems */

/** @var $_item \Appseconnect\B2BMage\Model\Quote\Item */
$_item = $block->getItem();
$_order = $_item->getQuote();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?php /* @noEscape */ echo $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?php /* @noEscape */ echo  __('SKU'); ?>: <?php /* @noEscape */ echo $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?php /* @noEscape */ echo  $option['label'] ?></em></strong></dt>
                <dd>
                    <?php /* @noEscape */ echo  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php /* @noEscape */ echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?php /* @noEscape */ echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?php /* @noEscape */ echo  $_item->getQty() * 1 ?></td>
    <td class="item-price">
        <?php /* @noEscape */ echo  $block->getItemPrice($_item); ?>
    </td>
</tr>
