<div class="list-header">
    <h2><?php echo __('My List'); ?></h2>
    <div class="filter-left">
        <form action="" method="post">
            <input type="text" name="search_list" id="search_list" placeholder="Search for a List" />
            <button type="submit" id="button_search">
                <span><i class="fa fa-search" aria-hidden="true"></i></span>
            </button>
        </form>
        <button type="button" id="button_list">
            <span><?php echo __('New List'); ?></span>
        </button>
    </div>
</div>
<?php $_gridrecords = $block->getCollection(); // get collection which we set in block class ?>
<?php if ($_gridrecords && count($_gridrecords)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col name"><?php echo __('List Name') ?></th>
                <th scope="col" class="col total"><?php echo __('List Total') ?></th>
                <th scope="col" class="col item"><?php echo __('Items') ?></th>
                <th scope="col" class="col edit"><?php echo __('Edit / View') ?></th>
                <th scope="col" class="col print"><?php echo __('Print') ?></th>
                <th scope="col" class="col delete"><?php echo __('Delete') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            $count = 0;
            foreach ($_gridrecords as $_gridrecord): ?>
                <tr <?php if ($count % 2 == 0) echo 'class="even"'; else echo 'class="odd"'; ?>>
                    <td class="col id"><?php echo $_gridrecord->getListName() ?></td>
                    <td class="col shipping"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_gridrecord->getTotalPrice(), true, false); ?></td>
                    <td class="col date"><?php echo $_gridrecord->getItem() ?></td>
                    <td class="col status"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></td>
                    <td class="col status"><i class="fa fa-print" aria-hidden="true"></i></td>
                    <td class="col status"><i class="fa fa-trash" aria-hidden="true"></i></td>
                </tr>
                <?php $count++; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.   ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('List records not available.'); ?></span></div>
<?php endif ?>
<script>
    require([
        'jquery',
        'jquery/ui'
    ], function($, modal) {
        $(window).load(function () {
            $('.customer-productlist .limiter-options').change(function(event){
                alert('ok');
                event.stopPropagation();
                event.preventDefault();
                return false;
            });
        });
    });
</script>
