<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();

$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);


?>
<?php $_order = $block->getOrder() ?>
<div class="actions-toolbar">
    <a href="<?php /* @noEscape */ echo $block->getPrintAllInvoicesUrl($_order) ?>"
       target="_blank"
       class="action print">
        <span><?php /* @noEscape */ echo __('Print All Invoices') ?></span>
    </a>
</div>
<?php foreach ($_order->getInvoiceCollection() as $_invoice): 

$pdfData = $_objectManager->create('Appseconnect\B2BMage\Helper\ErpDocs\Data')->getPdfData($_invoice->getIncrementId());
?>
<div class="order-title">
    <strong><?php /* @noEscape */ echo __('Invoice #') ?><?php /* @noEscape */ echo $_invoice->getIncrementId(); ?></strong>
    <a href="<?php /* @noEscape */ echo $block->getPrintInvoiceUrl($_invoice) ?>"
       onclick="this.target='_blank'"
       class="action print">
        <span><?php /* @noEscape */ echo __('Print Invoice') ?></span>
    </a>
    <?php
    if($pdfData):
    ?>
    <a href="<?php /* @noEscape */ echo $mediaUrl.$pdfData['pdf_path']; ?>" download
       onclick="this.target='_blank'"
       class="action print">
        <span><?php /* @noEscape */ echo __('Erp Invoice')?></span>
    </a>
    <?php
    endif;
    ?>
    
</div>
<div class="table-wrapper table-order-items invoice">
    <table class="data table table-order-items invoice" id="my-invoice-table-<?php /* @noEscape */ echo $_invoice->getId(); ?>">
        <caption class="table-caption"><?php /* @noEscape */ echo __('Items Invoiced') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?php /* @noEscape */ echo __('Product Name') ?></th>
                <th class="col sku"><?php /* @noEscape */ echo __('SKU') ?></th>
                <th class="col price"><?php /* @noEscape */ echo __('Price') ?></th>
                <th class="col qty"><?php /* @noEscape */ echo __('Qty Invoiced') ?></th>
                <th class="col subtotal"><?php /* @noEscape */ echo __('Subtotal') ?></th>
            </tr>
        </thead>
        <?php $_items = $_invoice->getAllItems(); ?>
        <?php $_count = count($_items) ?>
        <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getOrderItem()->getParentItem()) {
    continue;
} ?>
        <tbody>
            <?php /* @noEscape */ echo $block->getItemHtml($_item) ?>
        </tbody>
        <?php endforeach; ?>
        <tfoot>
            <?php /* @noEscape */ echo $block->getInvoiceTotalsHtml($_invoice)?>
        </tfoot>
    </table>
</div>
<?php /* @noEscape */ echo $block->getInvoiceCommentsHtml($_invoice)?>
<?php endforeach; ?>
