<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div id="quote_totals_block">
<table class="data-table admin__table-secondary order-subtotal-table">
    <?php $_totals = $block->getTotals('footer')?>

    <?php if ($_totals):?>
        <tfoot>
            <?php foreach ($block->getTotals('footer') as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?php /* @noEscape */ echo $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else:?>
                <tr class="col-<?php /* @noEscape */ echo $_code ?>">
                    <td <?php /* @noEscape */ echo $block->getLabelProperties() ?> class="label">
                        <strong><?php /* @noEscape */ echo $block->escapeHtml($_total->getLabel()) ?></strong>
                    </td>
                    <td <?php /* @noEscape */ echo $block->getValueProperties() ?>>
                        <strong><?php /* @noEscape */ echo $block->formatValue($_total) ?></strong>
                    </td>
                </tr>
                <?php endif?>
            <?php endforeach?>
        </tfoot>
    <?php endif?>
    
    
    
    

    <?php $_totals = $block->getTotals('')?>
    <?php if ($_totals):?>
        <tbody>
            <?php foreach ($_totals as $_code => $_total): ?>
                <?php if ($_total->getBlockName()): ?>
                    <?php /* @noEscape */ echo $block->getChildHtml($_total->getBlockName(), false) ?>
                <?php else:?>
                    <tr class="col-<?php /* @noEscape */ echo $_code ?>">
                        <td <?php /* @noEscape */ echo $block->getLabelProperties() ?> class="label">
                            <?php if ($_total->getStrong()):?>
                            <strong><?php /* @noEscape */ echo $block->escapeHtml($_total->getLabel()) ?></strong>
                            <?php else:?>
                            <?php /* @noEscape */ echo $block->escapeHtml($_total->getLabel()) ?>
                            <?php endif?>
                        </td>

                        <?php if ($_total->getStrong()):?>
                            <td <?php /* @noEscape */ echo $block->getValueProperties() ?>>
                                <strong><?php /* @noEscape */ echo $block->formatValue($_total) ?></strong>
                            </td>
                        <?php else:?>
                            <td <?php /* @noEscape */ echo $block->getValueProperties() ?>>
                                <span><?php /* @noEscape */ echo $block->formatValue($_total) ?></span>
                            </td>
                        <?php endif?>
                    </tr>
                <?php endif?>
                
            <?php endforeach?>
        </tbody>
    <?php endif?>
</table>
<!--   input type="text" style="width: 70%;">-->
</div>