<?php
$salesRepHelper = $this->helper('Appseconnect\B2BMage\Helper\Salesrep\Data');
?>
<?php if ($salesRepHelper->isAllow()) : ?>
<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare no-display" title="<?php /* @noEscape */ echo __('Compare Products') ?>"
       data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}"
    >
        <?php /* @noEscape */ echo __('Compare Products') ?>
        <span class="counter qty" data-bind="text: compareProducts().countCaption"></span>
    </a>
</li>
<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {
"Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
}}
</script>
<?php endif; ?>
