<?php $blockLayout = $this->getLayout()->createBlock('Magento\Cms\Block\Block'); ?>

<div class="service-request">
    <div class="container">
        <h2><?php echo __('Check Warranty'); ?></h2>
        <div class="note-block">
            <?php echo __('Note: Manufacturer’s warranty check is only applicable for serialized product.'); ?>
        </div>
        <div class="device-type" id="device-type">
            <h3><?php echo __('Device Type'); ?>:</h3>
            <div class="field-value">
                <ul>
                    <?php
                    $objectManager = $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
                    $categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
                    $categories = $categoryFactory->create()
                        ->addAttributeToSelect('*')
                        ->setStore($storeManager->getStore())
                        ->AddAttributeToFilter('show_in_service', '1');
                    foreach ($categories as $category) {
                        ?>
                        <li>
                            <img src="<?php echo $category->getImageUrl(); ?>"/>
                            <label for="dreamstation_type"><?php echo $category->getName(); ?></label>
                            <input type="hidden" class="device_type_image" value="<?= $category->getSerialImage() ?>"/>
                            <input type="radio" name="device_type" class="dreamstation_type" id="dreamstation_type" value="dreamstation"/>
                        </li>
                        <?php
                    }
                    ?>


                </ul>
                <div id="device-type-error" class="mage-error"></div>
            </div>
        </div>
        <?php echo $this->getChildHtml('global_messages'); ?>
        <form name="service_request" method="post"
              onsubmit="return validateForm()"
              id="service-request"
              data-mage-init='{"validation": {}}'
              enctype="multipart/form-data"
              action="<?php echo $this->getUrl('servicerequest/warranty/check') ?>">
            <input name="devicetype" id="devicetype" type="hidden" value="" />
            <input name="form_key" type="hidden" value="<?php /* @noEscape */
            echo $block->getFormKey(); ?>">
            <div class="device-details" id="device-details">
                <h3><?php echo __('Device Details'); ?>:</h3>
                <div class="field-value">
                    <div class="field-left">
                        <label><?php echo __('Serial #'); ?></label>
                        <div class="field-note">
                            <?php echo __('Click'); ?>
                            <a href="javascript:void(0)" title="here"
                               id="tooltip-serial-no"><?php echo __('here'); ?></a>
                            <?php echo __('if you need help to locate the Serial #') ?>
                        </div>
                    </div>
                    <div class="field-right">
                        <input type="text" class='serial_number' name="serial_number" id="serial_number"
                               data-validate="{required:true}"/>
                        <div id="serial-error"></div>
                    </div>
                </div>

                <div class="field-value">
                    <div class="field-left">
                        <label><?php echo __('Part No./SKU #'); ?></label>
                        <div class="field-note">
                            <?php echo __('Click'); ?>
                            <a href="javascript:void(0)" title="here"
                               id="tooltip-model-no"><?php echo __('here'); ?></a>
                            <?php echo __('if you need help to locate the Part No./SKU #'); ?>
                        </div>
                    </div>
                    <div class="field-right">
                        <input type="text" class='model_number' name="model_number" id="model_number"
                               data-validate="{required:true}"/>
                        <div id="serial-error"></div>
                    </div>
                </div>

                <div class="field-value-btn">
                    <button type="submit" class="validBtn"
                            name="valid_device" onclick="validateForm()"><?php echo __('Check Warranty'); ?></button>

                </div>
            </div>

        </form>
    </div>
</div>
<div class="img-popup"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Appseconnect_ServiceRequest/js/servicerequest": {}
        }
    }
</script>
<script type="text/javascript">
    var tooltipVal = '<img width="500" src="<?php echo $this->getViewFileUrl('Appseconnect_ServiceRequest::images/serial.jpg')?>"/>';
    tooltip_model_no = tooltipVal;
    tooltip_serial_no = tooltipVal;
</script>
<script>
    function validateForm(){
        var radios = document.querySelectorAll('input[type="radio"]:checked');
        var value = radios.length>0? radios[0].value: null;
        var errorDiv = document.getElementById("device-type-error");
        if(value == null){
            errorDiv.innerHTML = "Please select one of the device type";
            errorDiv.setAttribute('style','display:block');
            errorDiv.setAttribute('generated','true');
            return false;
        }
        document.getElementById('devicetype').setAttribute('value', value);
        errorDiv.setAttribute('style','display:none');
        return true;
    }
</script>
