<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$salesRepHelper = $this->helper('Appseconnect\B2BMage\Helper\Salesrep\Data');

$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
$scopeConfig = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface');
$guestCartDisabled = $scopeConfig->getValue('insync_category_visibility/select_checkout_visibility/active', $storeScope);

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @noEscape */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php /* @noEscape */ echo $block->getToolbarHtml() ?>
    <?php /* @noEscape */ echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @noEscape */ echo $viewMode; ?> products-<?php /* @noEscape */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product):
                $availabletopromiseHelper = $this->helper('Appseconnect\AvailableToPromise\Helper\DeliveryDate\Data')->getDeliveryDate($_product->getId());
                $getProductType = $this->helper('Appseconnect\AvailableToPromise\Helper\DeliveryDate\Data')->getProductType($_product->getId());
                ?>
                <?php /* @noEscape */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php /* @noEscape */ echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>">
                                <?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php /* @noEscape */ echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @noEscape */ echo $block->getProductPrice($_product) ?>
                        <?php /* @noEscape */ echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php /* @noEscape */ echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php /* @noEscape */ echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @noEscape */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php /* @noEscape */ echo $block->getBlockHtml('formkey');?>
                                            <?php if (($salesRepHelper->getType() == 2 || ($guestCartDisabled && !$customerSession->isLoggedIn())) || ($getProductType == 'simple' && empty($availabletopromiseHelper))): ?>
                                                <button disabled
                                                        type="submit"
                                                        title="<?php /* @noEscape */ echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary disabled">
                                                    <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php else :?>
                                                <button type="submit"
                                                        title="<?php /* @noEscape */ echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif;?>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @noEscape */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @noEscape */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php /* @noEscape */ echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php /* @noEscape */ echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>" title="<?php /* @noEscape */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @noEscape */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php /* @noEscape */ echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php /* @noEscape */ echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script>
    /**
     * This file will check that customer is logged in
     */
    require(
        ['jquery', 'Magento_Customer/js/customer-data','ko'],
        function ($, customerData,ko) {
            'use strict';

            var getCustomerInfo = function () {
                var customer = customerData.get('customer');

                return customer();
            };

            var isLoggedIn = function (customerInfo) {
                customerInfo = customerInfo || getCustomerInfo();

                return customerInfo && customerInfo.firstname;
            };

            return function () {
                var deferred = $.Deferred();
                var customerInfo = getCustomerInfo();

                if (customerInfo && customerInfo.data_id) {
                    deferred.resolve(isLoggedIn(customerInfo));
                } else {
                    customerData.reload(['customer'], false)
                        .done(function () {
                            deferred.resolve(isLoggedIn());
                        })
                        .fail(function () {
                            deferred.reject();
                        });
                }

                return deferred;
            };
        }
    );

</script>
