<?php
/** @var $block \Magento\Checkout\Block\Onepage\Link */
$checkoutHelper = $this->helper('\Appseconnect\AvailableToPromise\Helper\DeliveryDate\Data')->isDisable();
?>
<?php if ($block->isPossibleOnepageCheckout()) : ?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= $block->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
            data-mage-init='{
                "Magento_Checkout/js/proceed-to-checkout":{
                    "checkoutUrl":"<?= $block->escapeJs($block->escapeUrl($block->getCheckoutUrl())) ?>"
                }
            }'
            class="action primary checkout<?= ($checkoutHelper == 0) ? ' disabled' : '' ?>"
        <?php if ($block->isDisabled()) : ?>
            disabled="disabled"
        <?php endif; ?>>
        <span><?= $block->escapeHtml(__('Proceed to Checkout')) ?></span>
    </button>
<?php endif ?>
